project_name: check-mysql-strcmp
builds:
  - binary: check-mysql-strcmp
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ryuichi1208
    name: check-mysql-strcmp